# Generated by Django 4.2.5 on 2023-09-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailnotif', '0002_remove_customuser_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='family',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
