# Generated by Django 4.2.5 on 2023-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailnotif', '0004_customuser_active_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_newletter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
