# Generated by Django 4.2.5 on 2023-09-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailnotif', '0006_newsletter_delete_emaillog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='status',
            new_name='is_active',
        ),
    ]
